services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Oksydan\Falconize\:
    resource: '../src/*'
    exclude:
      - '../src/Container.php'
      - '../src/Falconize.php'
      - '../src/Handler'
      - '../src/**/DTO'
      - '../src/**/Collection'
      - '../src/Exception'

  Oksydan\Falconize\Service\PrepareConfiguration:
    class: Oksydan\Falconize\Service\PrepareConfiguration
    public: true

  Oksydan\Falconize\Yaml\Parser\YamlParser:
    class: Oksydan\Falconize\Yaml\Parser\YamlParser
    public: true

  Oksydan\Falconize\Handler\:
    resource: '../src/Handler/*'
    public: true
